<?php

use com\cminds\listmanager\App;
use com\cminds\listmanager\plugin\options\Options;
use com\cminds\listmanager\plugin\helpers\HTMLHelper;
use com\cminds\listmanager\plugin\taxonomies\TagTaxonomy;
use com\cminds\listmanager\plugin\shortcodes\Shortcode;
use com\cminds\listmanager\plugin\misc\Bookmarklet;
?>
<div class="clear"></div>
<hr />

<?php
echo do_shortcode(sprintf('[cminds_free_ads id=%s]', App::SLUG));
?>

<div class="cmlm">
    <?php
    /*
      <div class="card">
      <h2>Shortcodes</h2>
      <ol>
      <li>
      to display list use
      <code>[<?php echo Shortcode::SHORTCODE; ?>]</code> with <code>list</code>, <code>category</code> and <code>tag</code> attributes (you can use then at the same time to customize your list &mdash; they works like filters) where:
      <ul>
      <li>
      <code>list</code> is slug or list of slugs of <a href="edit-tags.php?taxonomy=cmlm_list">lists</a>, e.g.: <code>[<?php echo Shortcode::SHORTCODE; ?> list=list1,list2,...]</code>,
      </li>
      <li>
      <code>category</code> is slug or list of slugs of <a href="edit-tags.php?taxonomy=cmlm_category">categories</a>, e.g.: <code>[<?php echo Shortcode::SHORTCODE; ?> category=category1,category2,...]</code>,
      </li>
      <li>
      <code>tag</code> is slug or list of slugs of <a href="edit-tags.php?taxonomy=cmlm_tags">tags</a>, e.g.: <code>[<?php echo Shortcode::SHORTCODE; ?> tag=tag1,tag2,...]</code>,
      </li>
      </ul>
      </li>
      <li>
      to display single category (without search and filter on the top of the list) use
      <code>[<?php echo Shortcode::SHORTCODE; ?> category=category1]</code> where <code>category</code> attribute is slug of the <a href="edit-tags.php?taxonomy=cmlm_category">category</a>.
      </li>
      </ol>
      <p>
      To overwrite global setting of max number of links use <code>max_links</code> attribute (set 0 to remove limit) e.g.: <code>[<?php echo Shortcode::SHORTCODE; ?> category=category1 max_links=10]</code>.
      </p>
      </div>
     *
     */
    ?>
    <div class="card">
        <h2>Bookmarklet</h2>
        <p>
            Drag the bookmarklet below to your bookmarks bar. Then, when you’re on a page you want add to links collection, simply "press" it.
        </p>
        <p class="pressthis-bookmarklet-wrapper">
            <a class="pressthis-bookmarklet" onclick="return false;" href="<?php echo htmlspecialchars(Bookmarklet::getShortcutLink()); ?>"><span>Add This URL</span></a>
            <button type="button" class="button button-secondary pressthis-js-toggle js-show-pressthis-code-wrap" onclick="jQuery('#pressthis-code-wrap').slideDown();jQuery(this).fadeOut();return false;">
                <span class="dashicons dashicons-clipboard"></span>
                <span class="screen-reader-text">Copy bookmarklet code</span>
            </button>
        </p>
        <div style="display:none;" class="js-pressthis-code-wrap clear" id="pressthis-code-wrap">
            <p id="pressthis-code-desc">
                If you can't drag the bookmarklet to your bookmarks, copy the following code and create a new bookmark. Paste the code into the new bookmark's URL field.
            </p>
            <p>
                <textarea class="js-pressthis-code" rows="5" cols="120" readonly="readonly" onfocus="this.select();"><?php echo htmlentities(Bookmarklet::getShortcutLink()); ?></textarea>
            </p>
        </div>
    </div>
    <h2 class="nav-tab-wrapper">
        <a href="#cmlm-tab-plugin-options" data-for="general-options" class="nav-tab">Plugin Options</a>
        <a href="#cmlm-tab-plugin-appearance" data-for="plugin-appearance" class="nav-tab">Plugin Appearance</a>
    </h2>
    <form method="post">
        <div data-role="tab" data-tab="general-options" style="display: none;">
            <h3>General</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="columns_count">Number of columns *</label></th>
                    <td>
                        <input name="columns_count" type="number" min="1" max="10" id="columns_count" value="<?php echo intval(Options::getOption('columns_count')); ?>" class="regular-text" required="required" />
                        <p class="description">Number of columns generated by plugin.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="items_per_page">Items per page</label></th>
                    <td>
                        <input name="items_per_page" type="number" min="0" id="items_per_page" value="<?php echo intval(Options::getOption('items_per_page')) ?: ''; ?>" class="regular-text">
                        <p class="description">Max number of links displayed one page.<br />Leave empty to exclude pagination.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="favicons_display">Favicons display</label></th>
                    <td>
                        <input type="checkbox" id="favicons_display" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('favicons_display')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="favicons_display" value="<?php echo intval(Options::getOption('favicons_display')); ?>" />
                        <p class="description">
                            Disabling this option will disable the favicons functionality completely.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="favicons_local_cache">Favicons local cache</label></th>
                    <td>
                        <input type="checkbox" id="favicons_local_cache" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('favicons_local_cache')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="favicons_local_cache" value="<?php echo intval(Options::getOption('favicons_local_cache')); ?>" />
                        <p class="description">
                            Images with favicons will be locally saved as attached - this options <strong>is not</strong> recommend if you curate large lists (may cause performance issues).
                            <br />
                            Favicon for link is cached during adding or updating link entry.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="links_rel_nofollow">No follow</label></th>
                    <td>
                        <input type="checkbox" id="links_rel_nofollow" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('links_rel_nofollow')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="links_rel_nofollow" value="<?php echo intval(Options::getOption('links_rel_nofollow')); ?>" />
                        <p class="description">
                            <code>rel="nofollow"</code> will be added to links.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="links_target_blank">Open in a new window or tab</label></th>
                    <td>
                        <input type="checkbox" id="links_target_blank" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('links_target_blank')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="links_target_blank" value="<?php echo intval(Options::getOption('links_target_blank')); ?>" />
                        <p class="description">
                            Linked documents will be opened in a new window or tab.
                        </p>
                    </td>
                </tr>
                <?php /*
                  <tr>
                  <th scope="row"><label for="show_checkboxes">Show checkboxes</label></th>
                  <td>
                  <input type="checkbox" id="show_checkboxes" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_checkboxes')) ? 'checked="checked"' : ''; ?> />
                  <input type="hidden" name="show_checkboxes" value="<?php echo intval(Options::getOption('show_checkboxes')); ?>" />
                  <p class="description">
                  Show checkboxes before links which allow users mark visited addresses.
                  </p>
                  </td>
                  </tr>
                 */ ?>
            </table>
            <h3>Search and filter</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="show_search_and_filter">Show search and filter</label></th>
                    <td>
                        <input type="checkbox" id="show_search_and_filter" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_search_and_filter')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="show_search_and_filter" value="<?php echo intval(Options::getOption('show_search_and_filter')); ?>" />
                        <p class="description">
                            Show upper search field and categories filter.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="user_display_categories">Allow user to hide/show categories filter</label></th>
                    <td>
                        <input type="hidden" name="user_display_categories" value="0" />
                        <input type="checkbox" id="user_display_categories" name="user_display_categories" value="1" <?php checked(Options::getOption('user_display_categories'), '1'); ?> />

                        <p class="description">
                            Allow user to hide some categories in categories filter.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="show_bonus_info">Show additional information</label></th>
                    <td>
                        <input type="checkbox" id="show_bonus_info" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_bonus_info')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="show_bonus_info" value="<?php echo intval(Options::getOption('show_bonus_info')); ?>" />
                        <p class="description">
                            Show additional information below search field.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label>Labels in the category filter</label></th>
                    <td style="display:grid;">
                        <input name="label_search_placeholder" type="text" id="label_search_placeholder" value="<?php echo esc_attr(Options::getOption('label_search_placeholder')); ?>" class="regular-text">
                        <p class="description">Search input placeholder.</p>
                        <br/>
                        <input name="all_categories_label" type="text" id="all_categories_label" value="<?php echo esc_attr(Options::getOption('all_categories_label')); ?>" class="regular-text">
                        <p class="description">"All" label.</p>
                        <br/>
                        <input name="cmlm_category_label" type="text" id="cmlm_category_label" value="<?php echo esc_attr(Options::getOption('cmlm_category_label')); ?>" class="regular-text">
                        <p class="description">"category" label in the search input.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label>Label for category search input</label></th>
                    <td style="display:grid;">
                        <input name="label_for_search_input" type="text" id="label_for_search_input" value="<?php echo esc_attr(Options::getOption('label_for_search_input')); ?>" class="regular-text">
                        <p class="description">Search input label. Left blank to remove label.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="bonus_info_format">Additional information format</label></th>
                    <td>
                        <input name="bonus_info_format" type="text" id="bonus_info_format" value="<?php echo esc_attr(Options::getOption('bonus_info_format')); ?>" class="large-text">
                        <p class="description">Additional information displayed below search filed.<br /> Use <code>{last-update-date}</code> placeholder to display list last update date and <code>{links-count}</code> to display number of links.<br />You can use HTML entities (for example <code>&lt;br /&gt;</code> or <code>&lt;code&gt;</code>) to customize information format.</p>
                    </td>
                </tr>
            </table>
            <h3>Links order</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="link_order_by">Order by</label></th>
                    <td>
                        <select name="link_order_by">
                            <?php
                            foreach (array(
                        'default'        => 'Custom order',
                        'name_asc'       => 'By name ascending',
                        'name_desc'      => 'By name descending',
                        'edit_time_asc'  => 'By edit date ascending',
                        'edit_time_desc' => 'By edit date descending'
                            ) as $key => $value) {
                                echo sprintf('<option value="%s" %s> %s</option>', $key, $key == Options::getOption('link_order_by') ? 'selected="selected"' : '', $value);
                            }
                            ?>
                        </select>
                        <p class="description">Determine how links will be sorted.</p>
                    </td>
                </tr>
            </table>
            <h3>Category default view access</h3>
            <table class="form-table">
                <tr class="form-field">
                    <th scope="row" valign="top"><label for="term-link">Category view access</label></th>
                    <td>
                        <select name="category_access_list" id="term-access-list">
                            <option value='<?= Options::ALL_USERS ?>' <?= selected(Options::getOption('category_access_list'), Options::ALL_USERS, false); ?>>All</option>
                            <option value='<?= Options::REGISTERED_USERS ?>' <?= selected(Options::getOption('category_access_list'), Options::REGISTERED_USERS, false); ?>>Logged in users only</option>
                            <option value='<?= Options::SELECTED_ROLES ?>' <?= selected(Options::getOption('category_access_list'), Options::SELECTED_ROLES, false); ?>>Registered users with selected roles</option>
                            <option value='<?= Options::PERSONAL_ACCESS ?>' <?= selected(Options::getOption('category_access_list'), Options::PERSONAL_ACCESS, false); ?>>Personal (category author) access only</option>
                        </select>
                        <fieldset id="cmlm_roles_list" style="display:<?= (Options::getOption('category_access_list') == Options::SELECTED_ROLES) ? 'block' : 'none' ?>">
                            <?php
                            $access_roles = ( Options::getOption('category_access_list') == Options::SELECTED_ROLES ) ? Options::getOption('category_access_roles') : [Options::ADMIN_ROLE];
                            if (!in_array(Options::ADMIN_ROLE, $access_roles)) {
                                $access_roles[] = Options::ADMIN_ROLE;
                            }
                            $roles = wp_roles()->get_names();
                            foreach ($roles as $role) {
                                $role_slug = strtolower($role);
                                echo "<input type='checkbox' name='category_access_roles[]' value='$role_slug' " . checked(true, in_array($role_slug, $access_roles), false) . ">$role<br>";
                            }
                            ?>
                        </fieldset>
                        <p class="description">Who can view category by default</p>
                    </td>
                </tr>
            </table>
            <h3>Social Buttons</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="link_social_buttons">Show social share buttons</label></th>
                    <td>
                        <input type="checkbox" id="link_social_buttons" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('link_social_buttons')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="link_social_buttons" value="<?php echo intval(Options::getOption('link_social_buttons')); ?>" />
                        <p class="description">If enabled, social share buttons will be shown</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_social_buttons_in_new_line">Show social share buttons in new line</label></th>
                    <td>
                        <input type="checkbox" id="link_social_buttons_in_new_line" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('link_social_buttons_in_new_line')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="link_social_buttons_in_new_line" value="<?php echo intval(Options::getOption('link_social_buttons_in_new_line')); ?>" />
                        <p class="description">If enabled, social share buttons will be shown in new line</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_social_buttons_expand_on_hover">Show social share buttons on mouseover</label></th>
                    <td>
                        <input type="checkbox" id="link_social_buttons_expand_on_hover" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('link_social_buttons_expand_on_hover')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="link_social_buttons_expand_on_hover" value="<?php echo intval(Options::getOption('link_social_buttons_expand_on_hover')); ?>" />
                        <p class="description">If enabled, social share buttons chain will be shown on mouse move over share icon. If disabled, chain will be shown on click.</p>
                    </td>
                </tr>
            </table>
            <table class="form-table">
                <tr class="table-socials">
                    <th scope="row"><label>Social networks</label></th>
                    <td class="socials">
                        <p>Facebook</p>
                        <input type="checkbox" id="link_social_facebook" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('link_social_facebook')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="link_social_facebook" value="<?php echo intval(Options::getOption('link_social_facebook')); ?>" />
                    </td>
                    <td class="socials">
                        <p>Twitter</p>
                        <input type="checkbox" id="link_social_twitter" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('link_social_twitter')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="link_social_twitter" value="<?php echo intval(Options::getOption('link_social_twitter')); ?>" />
                    </td>
                    <td class="socials">
                        <p>LinkedIn</p>
                        <input type="checkbox" id="link_social_linkedin" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('link_social_linkedin')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="link_social_linkedin" value="<?php echo intval(Options::getOption('link_social_linkedin')); ?>" />
                    </td>
                    <td class="socials">
                        <p>Pinterest</p>
                        <input type="checkbox" id="link_social_pinterest" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('link_social_pinterest')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="link_social_pinterest" value="<?php echo intval(Options::getOption('link_social_pinterest')); ?>" />
                    </td>
                    <td class="socials">
                        <p>Reddit</p>
                        <input type="checkbox" id="link_social_reddit" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('link_social_reddit')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="link_social_reddit" value="<?php echo intval(Options::getOption('link_social_reddit')); ?>" />
                    </td>
                    <td class="socials">
                        <p>Tumblr</p>
                        <input type="checkbox" id="link_social_tumblr" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('link_social_tumblr')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="link_social_tumblr" value="<?php echo intval(Options::getOption('link_social_tumblr')); ?>" />
                    </td>
                    <td class="socials">
                        <p>Buffer</p>
                        <input type="checkbox" id="link_social_buffer" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('link_social_buffer')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="link_social_buffer" value="<?php echo intval(Options::getOption('link_social_buffer')); ?>" />
                    </td>
                </tr>
            </table>
            <h3>Link voting</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="link_like_button">Choose option</label></th>
                    <td>
                        <input type="hidden" name="link_like_button" value="0" />
                        <label>
                            <input type="radio" name="link_like_button" value="0" <?php checked('0', Options::getOption('link_like_button'), 1); ?> />
                            <p class="description">Disabled</p>
                        </label>
                    </td>
                    <td>
                        <label>
                            <input type="radio" name="link_like_button" value="1" <?php checked('1', Options::getOption('link_like_button'), 1); ?> />
                            <p class="description">Only allow link likes</p>
                        </label>
                    </td>
                    <td>
                        <label>
                            <input type="radio" name="link_like_button" value="2" <?php checked('2', Options::getOption('link_like_button'), 1); ?> />
                            <p class="description">Allow link upvote/downwote</p>
                        </label>
                    </td>
                </tr>
            </table>
            <h3>"NEW" tag</h3>
            <p>
                This feature allows you to automatically add tag to new or just edited links for specified time.
            </p>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="new_tag_id">Tag</label></th>
                    <td>
                        <?php
                        wp_dropdown_categories(array(
                            'show_option_none' => '&nbsp;',
                            'hide_empty'       => FALSE,
                            'selected'         => Options::getOption('new_tag_id'),
                            'name'             => 'new_tag_id',
                            'id'               => 'new_tag_id',
                            'taxonomy'         => TagTaxonomy::TAXONOMY,
                        ));
                        ?>
                        <p class="description">
                            "NEW" tag - added to new or updated links entries (leave empty to disable "NEW" tag feature).
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="new_tag_duration">Duration</label></th>
                    <td>
                        <select name="new_tag_duration" id="new_tag_duration">
                            <?php
                            foreach (array(
                        '1 day'    => 86400,
                        '2 days'   => 172800,
                        '3 days'   => 259200,
                        '5 days'   => 432000,
                        '1 week'   => 604800,
                        '2 weeks'  => 1209600,
                        '1 month'  => 2419200,
                        '3 months' => 7257600
                            ) as $k => $v) {
                                echo sprintf('<option value="%s" %s>%s</option>', $v, Options::getOption('new_tag_duration') == $v ? 'selected="selected"' : '', $k);
                            }
                            ?>
                        </select>
                        <p class="description">
                            How long "NEW" tag will be added.
                            <br />
                            Remember, if "NEW" tag is assigned directly to link, this option will not affect displaying it.
                        </p>
                    </td>
                </tr>
            </table>
        </div>
        <div data-role="tab" data-tab="plugin-appearance" style="display: none;">
            <h3>Categories</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="category_font_size">Font size</label></th>
                    <td>
                        <?php echo HTMLHelper::inputFontSize('category_font_size', Options::getOption('category_font_size'), array('class' => 'regular-text', 'id' => 'category_font_size')); ?>
                        <p class="description">Leave empty to use default.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="category_text_color">Text color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('category_text_color', Options::getOption('category_text_color'), array('class' => 'regular-text', 'id' => 'category_text_color')); ?>
                        <p class="description">Category title text color (clear to use default).</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="category_background_color">Background color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('category_background_color', Options::getOption('category_background_color'), array('class' => 'regular-text', 'id' => 'tooltip_bg_color')); ?>
                        <p class="description">Category title background color (clear to use default).</p>
                    </td>
                </tr>

            </table>
            <h3>Links</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="link_font_size">Font size</label></th>
                    <td>
                        <?php echo HTMLHelper::inputFontSize('link_font_size', Options::getOption('link_font_size'), array('class' => 'regular-text', 'id' => 'link_font_size')); ?>
                        <p class="description">Leave empty to use default.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_word_break">Word-break option</label></th>
                    <td>
                        <select name="link_word_break" onchange="document.getElementById('cmlm-example-element').style.wordBreak = this.value;">
                            <?php
                            foreach (array(
                        'break-all',
                        'break-word',
                        'keep-all',
                        'normal'
                            ) as $value) {
                                echo sprintf('<option value="%s" %s> %s</option>', $value, $value == Options::getOption('link_word_break') ? 'selected="selected"' : '', $value);
                            }
                            ?>
                        </select>
                        <p class="description">Determine how word wraps will be applied in the link title.</p>
                        <div id="example-wrapper"><span>Example:</span>
                            <div id="cmlm-example-element" class="transition-all" style="word-break: <?php echo Options::getOption('link_word_break'); ?>;">Honorificabilitudinitatibus califragilisticexpialidocious Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu
                                次の単語グレートブリテンおよび北アイルランド連合王国で本当に大きな言葉
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_title_color">Link title color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('link_title_color', Options::getOption('link_title_color'), array('class' => 'regular-text', 'id' => 'link_title_color')); ?>
                        <p class="description">Leave empty to use default..</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_show_subtitle">Show subtitle</label></th>
                    <td>
                        <input type="hidden" name="link_show_subtitle" value="0" />
                        <input name="link_show_subtitle" type="checkbox" id="link_show_subtitle" value="1" <?php checked(Options::getOption('link_show_subtitle'), true); ?> class="regular-text">
                        <p class="description">Show subtitle under link</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_subtitle_font_size">Subtitle font size</label></th>
                    <td>
                        <?php echo HTMLHelper::inputFontSize('link_subtitle_font_size', Options::getOption('link_subtitle_font_size'), array('class' => 'regular-text', 'id' => 'link_subtitle_font_size')); ?>
                        <p class="description">Leave empty to use default.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_hover_color">Subtitle color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('link_subtitle_color', Options::getOption('link_subtitle_color'), array('class' => 'regular-text', 'id' => 'link_subtitle_color')); ?>
                        <p class="description">Leave empty to use default.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_hover_color">Hover background color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('link_hover_color', Options::getOption('link_hover_color'), array('class' => 'regular-text', 'id' => 'link_hover_color')); ?>
                        <p class="description">Links hover background color (clear to use default).</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="tagfile_link_background_color">Tag-file links background color</label></th>
                    <td>
                        <?php
                        echo "<label>Tag-file link 1</label>";
                        echo HTMLHelper::inputColor('tagfile1_link_background_color', Options::getOption('tagfile1_link_background_color'), array('class' => 'regular-text', 'id' => 'tagfile_link_background_color'));
                        echo "<label>Tag-file link 2</label>";
                        echo HTMLHelper::inputColor('tagfile2_link_background_color', Options::getOption('tagfile2_link_background_color'), array('class' => 'regular-text', 'id' => 'tagfile_link_background_color'));
                        echo "<label>Tag-file link 3</label>";
                        echo HTMLHelper::inputColor('tagfile3_link_background_color', Options::getOption('tagfile3_link_background_color'), array('class' => 'regular-text', 'id' => 'tagfile_link_background_color'));
                        ?>
                        <p class="description">Default value is white (#FFFFFF)</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_image_height">Image height</label></th>
                    <td>
                        <input name="link_image_height" type="text" id="link_image_height" value="<?php echo esc_attr(Options::getOption('link_image_height')); ?>" class="regular-text" placeholder="e.g. 30px">
                        <p class="description">Height of images in links. Leave empty for auto size.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_image_width">Image width</label></th>
                    <td>
                        <input name="link_image_width" type="text" id="link_image_width" value="<?php echo esc_attr(Options::getOption('link_image_width')); ?>" class="regular-text" placeholder="e.g. 30px">
                        <p class="description">Width of images in links. Leave empty for auto size.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_video_height">Video height</label></th>
                    <td>
                        <input name="link_video_height" type="text" id="link_video_height" value="<?php echo esc_attr(Options::getOption('link_video_height')); ?>" class="regular-text" placeholder="e.g. 315px">
                        <p class="description">Height of videos in links. Leave empty for auto size.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_video_width">Video width</label></th>
                    <td>
                        <input name="link_video_width" type="text" id="link_video_width" value="<?php echo esc_attr(Options::getOption('link_video_width')); ?>" class="regular-text" placeholder="e.g. 560px">
                        <p class="description">Width of videos in links. Leave empty for auto size.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_opacity">Link opacity</label></th>
                    <td>
                        <input name="link_opacity" type="number" min="0" max="1" step="0.05" id="link_opacity" value="<?php echo esc_attr(Options::getOption('link_opacity')); ?>" class="regular-text">
                        <p class="description">Link opacity (from 0 to 1).</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="show_tagfile_icon">Show attachment icons</label></th>
                    <td>
                        <input type="hidden" name="show_tagfile_icon" value="0" />
                        <input name="show_tagfile_icon" type="checkbox" id="show_tagfile_icon" value="1" <?php checked(Options::getOption('show_tagfile_icon'), true); ?> class="regular-text">
                        <p class="description">Show file-type icon of attached files.</p>
                    </td>
                </tr>
            </table>
            <h3>Tooltips</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="show_tooltip_on_category">Show tooltips</label></th>
                    <td>
						<input type="checkbox" id="show_tooltip_on_category" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_tooltip_on_category')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="show_tooltip_on_category" value="<?php echo intval(Options::getOption('show_tooltip_on_category')); ?>" />
                        <p class="description">
                            Show tooltips on category filter.
                        </p>
					</td>
                </tr>
                <tr>
                    <th scope="row"><label for="tooltip_font_size">Font size</label></th>
                    <td>
                        <?php echo HTMLHelper::inputFontSize('tooltip_font_size', Options::getOption('tooltip_font_size'), array('class' => 'regular-text', 'id' => 'tooltip_font_size')); ?>
                        <p class="description">Leave empty to use default.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="tooltip_text_color">Text color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('tooltip_text_color', Options::getOption('tooltip_text_color'), array('class' => 'regular-text', 'id' => 'tooltip_bg_color')); ?>
                        <p class="description">Tooltips text color (clear to use default).</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="tooltip_background_color">Background color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('tooltip_background_color', Options::getOption('tooltip_background_color'), array('class' => 'regular-text', 'id' => 'tooltip_bg_color')); ?>
                        <p class="description">Tooltips background color (clear to use default).</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="tooltip_border_color">Border color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('tooltip_border_color', Options::getOption('tooltip_border_color'), array('class' => 'regular-text', 'id' => 'tooltip_bg_color')); ?>
                        <p class="description">Tooltips border color (clear to use default).</p>
                    </td>
                </tr>

            </table>
            <h3>Social network Buttons</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="icon_size">Button size</label></th>
                    <td>
                        <?php echo HTMLHelper::inputFontSize('icon_size', Options::getOption('icon_size'), array('class' => 'regular-text', 'id' => 'icon_size')); ?>
                        <p class="description">Default size is 25px.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="icon_opacity">Button opacity</label></th>
                    <td>
                        <input name="icon_opacity" type="number" min="0" max="1" step="0.05" id="icon_opacity" value="<?php echo esc_attr(Options::getOption('icon_opacity')); ?>" class="regular-text">
                        <p class="description">Button opacity (from 0 to 1).</p>
                    </td>
                </tr>
            </table>
            <h3>For Event list</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="show_event_date">Show event date</label></th>
                    <td>
                        <input type="checkbox" id="show_event_date" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_event_date')) ? 'checked="checked"' : ''; ?> autocomplete="off" />
                        <input type="hidden" name="show_event_date" value="<?php echo intval(Options::getOption('show_event_date')); ?>" />
                        <p class="description">
                            Show event date under name of link
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="show_sortby_event_date">Show sorting by event date</label></th>
                    <td>
                        <input type="checkbox" id="show_sortby_event_date" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_sortby_event_date')) ? 'checked="checked"' : ''; ?> autocomplete="off" />
                        <input type="hidden" name="show_sortby_event_date" value="<?php echo intval(Options::getOption('show_sortby_event_date')); ?>" />
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="event_date_font_size">Font size</label></th>
                    <td>
                        <?php echo HTMLHelper::inputFontSize('event_date_font_size', Options::getOption('event_date_font_size'), array('class' => 'regular-text', 'id' => 'event_date_font_size')); ?>
                        <p class="description">Leave empty to use default.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="event_date_font_style">Font style option</label></th>
                    <td>
                        <select name="event_date_font_style">
                            <?php
                            foreach (array(
                                'normal',
                                'italic',
                            ) as $value) {
                                echo sprintf('<option value="%s" %s> %s</option>', $value, $value == Options::getOption('event_date_font_style') ? 'selected="selected"' : '', $value);
                            }
                            ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="event_date_text_color">Text color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('event_date_text_color', Options::getOption('event_date_text_color'), array('class' => 'regular-text', 'id' => 'event_date_text_color')); ?>
                        <p class="description">Event date text color (clear to use default).</p>
                    </td>
                </tr>

            </table>
        </div>
        <input type="hidden" name="cmlm_action_update" value="1" />
        <input type="hidden" name="nonce" value="<?php echo wp_create_nonce('cmlm_action_update'); ?>" />
        <?php submit_button(); ?>
        <small>* - required fields</small>
    </form>
</div>

<style type="text/css">
    .cmlm h2.nav-tab-wrapper{
        margin-top: 20px;
    }
    .cmlm .nav-tab{
        box-shadow: none;
    }
    .cmlm .card{
        max-width: none;
    }
</style>
<script type="text/javascript">
    (function ($) {
        "use strict";
        $('.cmlm .nav-tab').on('click', function () {
            $('.cmlm .nav-tab').removeClass('nav-tab-active');
            $(this).addClass('nav-tab-active');
            $('.cmlm *[data-role="tab"]').hide();
            $('.cmlm *[data-role="tab"][data-tab="' + $(this).data('for') + '"]').show();
        });
        if ($('.cmlm a[href="' + window.location.hash + '"]').click().length != 1) {
            $('.cmlm a.nav-tab').first().click();
        }
        $('.cmlm input[type="submit"]').on('click', function () {
            if ($('.cmlm form').find(':invalid')) {
                var tab = $('.cmlm form').find(':invalid').first().parents('*[data-role="tab"]').data('tab');
                $('.cmlm').find('a[data-for="' + tab + '"]').click();
            }
        });
    })(jQuery);
</script>
